/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'A fresh start': '一个新的开始',
    'A well filled bag': '一个装满的袋子',
    'Actions': '行动',
    'AP Pistol': 'AP手枪',
    'Base Damage': '基础伤害',
    'Baseball Bat': '棒球棒',
    'Battle Axe': '战斧',
    'Brass Knuckles': '指节铜环',
    'Buy': '购买',
    'Bunker': '地堡',
    'Cash': '现金',
    'Close': '关闭',
    'Donate': '捐赠',
    'Fist': '拳头',
    'Fleeca Heist': '弗莱卡抢劫',
    'Current version v': '当前版本 v',
    'Cocaine': '可卡因',
    'Time Trial': '计时赛',
    'Weapons': '武器',
    'Weapon': '武器',
    'Weed dealer': '大麻经销商',
    'Weed Farm': '大麻农场',
    'Widowmaker': '寡妇制造者',
    'Wrench': '扳手',
    'You can get': '你会得到',
    'You can currently get': '你当前会得到',
    'You can also reset your save to to start a new game.': '您也可以重置存档以开始新游戏。',
    'You are actually using the character number': '您实际上在使用的字符编号',
    'Knife': '刀',
    'Import': '导入',
    'Level': '等级',
    'Menu': '菜单',
    'Message': '消息',
    'Meth': '冰毒',
    'Micro SMG': '微型冲锋枪',
    'Mission': '任务',
    'Missions': '任务',
    'Musket': '步枪',
    'Next': '下一个',
    'Others': '其它',
    'Objectives': '目标',
    'Objective': '目标',
    'Nightstick': '警棍',
    'per click.': '每次点击。',
    'per second.': '每秒。',
    'Pickpocket': '扒手',
    'Price': '价格',
    'Player': '玩家',
    'Prison Break': '越狱',
    'Rank': '等级',
    'Railgun': '轨道炮',
    'Save': '保存',
    'Reset': '重置',
    'Roll stats': '随机属性',
    'Shotguns': '猎枪',
    'Sell': '出售',
    'Statistics': '统计',
    'Stun Gun': '电击枪',
    'Success': '成功',
    'Successfully completed the tutorial.': '成功完成了教程。',
    'Series A Funding': 'A轮融资',
    'Series A Funding Heist': 'A轮融资抢劫',
    'Human Labs': '人体实验室',
    'eavy Weapons': '重型武器',
    'Guide': '指南',
    'Guide - Presentation': '指南 - 演示',
    'Gusenberg Sweeper': '古腾堡清洁工',
    'Handguns': '手枪',
    'Hangar': '机库',
    'Heavy Pistol': '重型手枪',
    'Heavy Revolver Mk II': '重型左轮手枪Mk II',
    'Heavy Shotgun': '重型猎枪',
    'Character': '字符编号',
    'Damage multiplier at': '伤害加成在',
    'Damages upgrades bought': '购买的伤害升级',
    'Export': '导出',
    'Vehicles': '汽车',
    'Value': '价值',
    'Use your weapon': '使用你的武器',
    'Upgrade': '升级',
    'Up-n-Atomizer': 'Up-n雾化器',
    'Unholy Hellbringer': '邪恶的地狱使者',
    'The trilliard': '台球',
    'The fleeca Bank': '羊毛银行',
    'The punisher': '惩罚者',
    'The eagle nest': '鹰巢',
    'The beginning of wealth': '财富的开始',
    'Strength': '力量',
    'Skill': '技能',
    'Produce': '生产',
    'Prestige': '声望',
    'Points': '点数',
    'Previous': '上一个',
    'Pistol Mk II': '手枪Mk II',
    'Pistol .': '手枪 .',
    'Reasign Points': '分配点',
    'Sawed-Off Shotgun': '削短型霰弹枪',
    'Security Van Heist': '保安车抢劫',
    'Street Race': '街头竞赛',
    'Street boss': '小头目',
//    'Pickpocketing': '扒窃',
    'Heavy Weapons': '重型武器',
    'Heavy Sniper Mk II': '重型狙击Mk II',
    'Golf Club': '高尔夫俱乐部',
    'Homing Launcher': '归位发射器',
    'Assault Riffle Mk II': '突击步枪Mk II',
    'Assault Rifles': '突击步枪',
    'Armored van stalker': '装甲的追猎者',
    'Bullpup Shotgun': '小斗犬猎枪',
    'Breaking five': '破五',
    'Machete': '大砍刀',
    'Machine Guns': '机枪',
    'Machine Pistol': '全自动手枪',
    'Manage': '管理',
    'Manufacturer of false money': '假币制造者',
    'Manufacturer of false papers': '伪造文件者',
    'Marksman Rifle Mk II': '神射手步枪Mk II',
    'Humane Labs Raid': '人道实验室突袭',
    'Melee Weapons': '近战武器',
    'Minigun': '迷你枪',
    'Multipliers': '倍数',
    'New objective': '新目标',
    'New objective for': '新目标',
    'Objective completed !': '目标完成！',
    'Once you have the required': '一旦您具有所需的',
    'Pacific Standard': '太平洋标准',
    'Pacific Standard Heist': '太平洋标准抢劫',
    'Pickpocketing': '扒窃',
    'Prestige multiplier at': '声望倍数在',
    'Prison Break Heist': '越狱抢劫',
    'Professionnal car dealer': '专业汽车经销商',
    'Purchase': '购买',
    'Reach the rank': '达到等级',
    'rob 100 armored vans.': '抢劫100辆运钞车。',
    'rob 100 grocery stores.': '抢劫100家杂货店。',
    'Rob a hundred times human labs.': '抢劫人类实验室100次。',
    'rob the fleeca bank a hundred times..': '抢劫羊毛银行100次。',
    'Rob the union depository a hundred times.': '抢劫联邦仓库100次。',
    'Sniper Rifle': '狙击步枪',
    'Sniper Rifles': '狙击步枪',
    'Stamina': '耐力',
    "The big score": "大比分",
    "The billiardaire": "台球",
    'The billionaire': '亿万富翁',
    'The first dollar': '第一桶金',
    'The millionaire': '百万富翁',
    'win 100 street races.': '赢得100场街头比赛。',
    'with this objective.': '达到这个目标。',
    'you can change your character and get Character Points (CP': '您可以更改角色并获得角色点数（CP',
    'You must reach the rank': '你必须达到等级',
    'you need Character Points (CP) to upgrade them.': '您需要角色点（CP）进行升级。',
    'Zombie apocalypse': '僵尸启示录',
    ' for the cash multiplier': '对于现金倍数',
    ' for the damage multiplier': '对于伤害倍数',
    ' Rank': ' 等级',
    'Action': '动作',
    'and': '和',
    'and get': '和获得',
    'and played for': '并玩了',
    'and rank,': '和等级,',
    'Announce': '声明',
    'Assault Shotgun': '突击霰弹枪',
    'Assault SMG': '突击SMG',
    'Attack 100 gangs.': '攻击100个帮派。',
    'Bonus': '奖励',
    'Change Character': '更改角色',
    'Casino Heist': '赌场抢劫',
    'Character number': '角色数量',
    'Current prestige multiplier at': '当前的声望倍数为',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    'Here you can export your save to another naviator or computer.': '在这里，您可以将存档内容导出到另一台设备或计算机。',
    'Guide - Character Skills': '指南-角色技能',
    'Grocery Store Robbery': '杂货店抢劫',
    'Grocery stalker': '杂货店跟踪狂',
    'Grenade Launcher': '榴弹发射器',
    'Gang Attack': '帮派攻击',
    'for earnt cash & damages.': '赚取现金和赔偿金。',
    'Fast & Furious': '速度与激情',
    'Evade the prison a hundred times.': '逃狱100次。',
    'Double Barrel Shotgun': '双管猎枪',
    'Document Forgery': '伪造文件',
    'Doomsday Heist': '末日抢劫',
    'Do the pacific standard heist a hundred times.': '进行太平洋标准抢劫100次。',
    'Do the doomsday heist a hundred times.': '末日抢劫100次。',
    'Do series a funding a hundred times.': '进行100次A轮融资。',
    'Counterfeit Cash': '伪造现金',
    'Complete 100 time trials.': '完成100次审讯。',
    'Compact Rifle': '紧凑型步枪',
    'Cocaine manufacturer': '可卡因制造商',
    'Character Points (CP) for your new character.': '新角色的角色点（CP）。',
    'Cash multiplier upgrades bought': '购买的现金倍数升级',
    'Cash multiplier at': '现金倍数在',
    'by using your weapons or by doing missions.': '通过使用你的武器或执行任务。',
    'Buying an Activity will increase your rank and you need that to change your character.': '购买一个活动将增加你的等级，你需要它来改变你的角色。',
    'Buy a total of 100 bunkers.': '累计购买100个碉堡。',
    'Buy a total of 100 cocaine workshops.': '累计购买100个可卡因作坊。',
    'Buy a total of 100 meth workshops.': '累计购买100个bing毒作坊。',
    'Buy a total of 100 hangars.': '累计购买100个机库。',
    'buy 100 weed farms.': '买100个大麻农场。',
    'buy 100 false papers factories.': '买100个假证工厂。',
    'buy 100 false money factories.': '买100个假币工厂。',
    'But, with a different vision and a different gameplay of the original game.': '但是，具有与原始游戏不同的视野和不同的游戏玩法。',
    'but it will become more expensive.': '但它会变得更昂贵。',
    'After you got some cash, you can buy a weapon or start a mission to gain a lot more': '有了现金后，您可以购买武器或开始执行任务以获取更多收益',
    'Advanced Rifle': '高级步枪',
    'A whole suitcase': '一整个行李箱',
    'A whole handful': '一把',
    'Weapons are used to do more damage and get \'manually\' an amount of': '武器被用来造成更大的伤害并“手动”获得一定数量的',
    'You can start by clicking on the fist to make some money.': '您可以通过点击第一个赚一些钱开始。',
    'Vehicle Trafficking': '车辆贩运',
    'Union Depository Heist': '联邦储蓄抢劫',
    'to switch to another character.': '切换到另一个字符。',
    'To do that, you have to get': '为此，您必须获得',
    'This is the prestige system of the game.': '这是游戏的声望系统。',
    'times more.': '次。',
    'This is the main mechanic of the game, they are used to automate the game.': '这是游戏的主要机制，它们用于使游戏自动化。',
    'They are used to increase your cash and damage multipliers,': '它们用于增加您的现金和伤害倍数，',
    'there is also a random quality system applied to the weapons that can raise or lower the power of the weapon.': '还有一种随机质量体系应用于武器，可以提高或降低武器的威力。',
    'The more you have the more you get': '拥有的越多，得到的越多',
    'The main goal of the game is to buy every cars and weapons in the game.': '游戏的主要目标是购买游戏中的所有汽车和武器。',
    'It will cost all your Weapons, Money and Missions but you keep all your Vehicles.': '它将花费你所有的武器，金钱和任务，但你保留所有的车辆。',
    'in your pockets.': '在你的口袋里。',
    'IdleFive is a GTA-Like game but inside an idle game environnement.': '《GTA放置》是一款类似于《侠盗猎车手》(gta)的游戏，但却是在一个空闲的游戏环境中。',
    'I want to thank you for playing this little game that i created.': '我想感谢你们玩了我做的这个小游戏。',

    //原样
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "Pump Shotgun Mk": "泵式霰弹枪",
    "SMG Mk": "SMG Mk",
    "SNS Pistol Mk": "SNS手枪Mk",
    "Special Carbine Mk": "特种卡宾枪",
    "The army of ": "军队",
    "You started the ": "您开始玩游戏从 ",
    "Bullpup Rifle Mk": "无托步枪Mk",
    "Carbine Rifle Mk": "卡宾步枪MK",
    "Combat MG Mk": "战斗MG Mk",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    " ": "",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    "\n": "",
    " Heavy Weapons acquired.": "获得的重型武器。",
    " Machine Guns acquired.": "获得的机关枪。",
    " Shotguns acquired.": "获得的散弹枪。",
    " Sniper Rifles acquired.": "获得的狙击步枪。",
    " CP": "角色点",
    " Objectives completed.": "目标已完成。",
    " remaining uses required.": "剩余的使用要求。",
    " Melee Weapons acquired.": "获得的近战武器。",
    " weapons acquired.": "获得的武器。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^x?\d+(\.\d+)?[A-Za-z%]{0,2}(\s.C)?\s*$/, //12.34K,23.4 °C
    /^x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /^\s*$/, //纯空格
    /^\d+(\.\d+)?[A-Za-z]{0,2}.?\(?([+\-]?(\d+(\.\d+)?[A-Za-z]{0,2})?)?$/, //12.34M (+34.34K
    /^(\d+(\.\d+)?[A-Za-z]{0,2}\/s)?.?\(?([+\-]?\d+(\.\d+)?[A-Za-z]{0,2})?\/s\stot$/, //2.74M/s (112.4K/s tot
    /^\d+(\.\d+)?(e[+\-]?\d+)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?$/, //2.177e+6 (+4.01+4
    /^(\d+(\.\d+)?(e[+\-]?\d+)?\/s)?.?\(?([+\-]?(\d+(\.\d+)?(e[+\-]?\d+)?)?)?\/s\stot$/, //2.177e+6/s (+4.01+4/s tot
];
var cnExcludePostfix = [
    /:?\s*x?\d+(\.\d+)?(e[+\-]?\d+)?\s*$/, //12.34e+4
    /:?\s*x?\d+(\.\d+)?[A-Za-z]{0,2}$/, //: 12.34K, x1.5
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
var cnRegReplace = new Map([
    [/^\/(.+) success obtained./, '\/$1 获得成功。'],
    [/^(.+) Assault Rifles acquired./, '\/获得 $1 突击步枪。'],
    [/^(.+) points spent./, '\/花费了 $1 点数。'],
    [/^(.+) Handguns acquired./, '\/获得 $1 手枪。'],
    [/^New objective for\n(.+)/, '新的目标'],
    [/^Reached rank (.+).$/, '达到等级 $1 。'],
    [/^You've gained (.+).$/, '你已经赚了 $1。'],
    [/^Clicked (.+) times.$/, '点击了 $1 次。'],
    [/^Steal (.+) vehicles.$/, '偷了 $1 辆车。'],
    [/^hired (.+) pickpockets.$/, '雇佣 $1 个扒手。'],
    [/^You have unlocked the character number (.+).$/, '您已解锁字符编号$1。'],
    [/^(\d+) hour (\d+) minutes$/, '$1 小时 $2 分钟'],
    [/^(\d+) hour (\d+) minutes (\d+) second$/, '$1 小时 $2 分钟 $3 秒'],
    [/^\n(.+)Rank$/, '等级'],
    [/^\n(.+)Announce\n(.+)$/, '声明'],
    [/^(.+) minutes (.+) seconds$/, '$1 分 $2 秒'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);